language: node_js
node_js:
 - 12
deploy:
 provider: heroku
 api_key:
  secure: L2Cfzei5/Y46rVSfFsIv76ksm+rhSxtEqLWOb95mxezMjtz0E3rsteUNeLA1LS1qVY4rLwVjH9Q+YWOuz0TFvAetVXoQJcXYj0izAnX27RH5hXI93V1HYrgJJRs3P8qTGT+ujH2Rq40HDaFzl4h5AUz2ANyFwjDh6If5n8N4HCDTNKI1SfZMoMG/qHQwcPqZI85IzJiIa8MxLWKsXmbE+ihRPNzmCxJkcHQQJy+vbiUquGO0j7vIKeoxG+z2cxkDQRevT9UXxAQnkTvv0WMC7e5Ljq4xYfsUuv5FbvuW/EqjCJwT720kr3aBmeFk8Cn1T+B35NK3Bux3V6zM9qkGnsieh+duz96cbdwIN9I0PNctIP8eOMWN2NgM5A+TxlBmZCo3lPIHiN8gdVDtt4Yiw0OcKQHCFQHhY6m7i8vE605DcNSYubLAmXGCe1kqYWsCKouM/Angu0WULtlDjdZukjPCgOlGlU+2F3pjJR+z9OWP/Jykdx267oY1ER30Zfr3axXRUBRpdotCCp6CiPVBl3VtYoQt2bF5Mf1KABU+quyifPHkWHPU8kghDe1my0WlR4qnW3Eb8AnpKC97YUGaUIrBwxEgm/2xThxuuEigOw8H+nLzhbF1IqKwRkDEKRGHzIKNWjIh6TffascSB7SafAUQQ411Jg8YC+KHm880nsE=
 app: ewydra-blog
